name: Test Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run dev
      id: tag_dev
      run: |
        GITHUB_REF=refs/tags/v1.0.0 node main.js

    - name: Test dev
      run: |
        test "v1.0.0" = "$GIT_TAG_NAME"

    - name: Run dev without prefix v
      id: tag_dev_without_prefix_v
      run: GITHUB_REF=refs/tags/v1.0.0 INPUT_WITHOUT_PREFIX_V=true node main.js
    
    - name: Test dev without prefix v
      run: |
        test "1.0.0" = "${{steps.tag_dev.outputs.tag}}"
    
    - name: Run prod
      id: tag_prod
      if: startsWith(github.ref, 'refs/tags') == true
      uses: ./
    
    - name: Test prod
      if: startsWith(github.ref, 'refs/tags') == true
      run: |
        test -n "$GIT_TAG_NAME"
